//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttMachineTableRefrence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttMachineTableRefrence()
        {
            this.AttendanceLogs = new HashSet<AttendanceLog>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<int> TableID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceLog> AttendanceLogs { get; set; }
        public virtual AttMachine AttMachine { get; set; }
        public virtual AttTableDefination AttTableDefination { get; set; }
    }
}
