//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttMachine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttMachine()
        {
            this.AttMachineTableRefrences = new HashSet<AttMachineTableRefrence>();
        }
    
        public int MachId { get; set; }
        public string MachineName { get; set; }
        public Nullable<int> SenarioID { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        public virtual Senario Senario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttMachineTableRefrence> AttMachineTableRefrences { get; set; }
    }
}
